import { PutCommand, GetCommand, QueryCommand, UpdateCommand } from '@aws-sdk/lib-dynamodb';
import { v4 as uuidv4 } from 'uuid';
import { docClient, TABLES } from '../config/dynamodb';
import type { Lesson } from '../types';

/**
 * Stub lesson generator. Returns a placeholder lesson record.
 * Will be replaced by the Generator Agent's video content pipeline.
 */
export async function generateLesson(
  childId: string,
  sessionId: string,
  topic: string,
  triggerQuestionId: string
): Promise<Lesson> {
  const lesson: Lesson = {
    lessonId: uuidv4(),
    sessionId,
    childId,
    topic,
    videoUrl: `https://placeholder.allnighters.app/lessons/${topic}/remedial.mp4`,
    description: `Remedial lesson on ${topic}. This is a placeholder — real content will be generated by the AI pipeline.`,
    durationSeconds: 120,
    watchCount: 0,
    triggerQuestionId,
    createdAt: new Date().toISOString(),
  };

  await docClient.send(
    new PutCommand({ TableName: TABLES.LESSONS, Item: lesson })
  );
  return lesson;
}

export async function getLesson(lessonId: string): Promise<Lesson | null> {
  const result = await docClient.send(
    new GetCommand({ TableName: TABLES.LESSONS, Key: { lessonId } })
  );
  return (result.Item as Lesson) || null;
}

export async function getLessonBySession(sessionId: string): Promise<Lesson | null> {
  const result = await docClient.send(
    new QueryCommand({
      TableName: TABLES.LESSONS,
      IndexName: 'sessionId-index',
      KeyConditionExpression: 'sessionId = :sid',
      ExpressionAttributeValues: { ':sid': sessionId },
    })
  );
  return (result.Items?.[0] as Lesson) || null;
}

export async function incrementWatchCount(lessonId: string): Promise<void> {
  await docClient.send(
    new UpdateCommand({
      TableName: TABLES.LESSONS,
      Key: { lessonId },
      UpdateExpression: 'SET watchCount = watchCount + :inc',
      ExpressionAttributeValues: { ':inc': 1 },
    })
  );
}
